# Generated by Django 5.0.5 on 2024-05-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('get', models.URLField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='asset',
            name='get',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='asset',
            name='thumbnail',
            field=models.URLField(),
        ),
    ]
