# Generated by Django 5.0.6 on 2024-05-25 09:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0002_textpdf_alter_asset_get_alter_asset_thumbnail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.AddField(
            model_name='textpdf',
            name='descr',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='textpdf',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
